codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: auto
        threshold: 80%
  precision: 2
  round: down
  range: "20...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

fixes:
  - "/code::"

ignore:
  - "/code/ows_cfg_example.py"  # ignore cfg_example as it serves as reference

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
