services:
  ows_18:
    cap_add:
      - SYS_PTRACE
    depends_on:
      postgres:
        condition: service_healthy

  pyspy:
    build: docker/pyspy/
    pid: "host"
    privileged: true
    volumes:
    - .:/profiles
