version: '3.4'

services:
  postgres:
    # db with some data from ls8_usgs_level1_scene pre-indexed
    build: docker/database/
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    ports:
      - 5432:5432
    restart: always

  ows:
    build:
      context: .
    environment:
      # Overwrite db config to point to pre-indexed-db
      DB_HOSTNAME: postgres
      DB_PORT: "5432"
      DB_USERNAME: opendatacube
      DB_PASSWORD: opendatacubepassword
      DB_DATABASE: opendatacube

    volumes:
      - ./ows_test_cfg.py:/env/config/ows_cfg.py
    depends_on:
      - postgres