# Default compose will create an ows image, with dev settings and connect to a local db
services:
  ows:
    build:
      context: .
      args:
        PYDEV_DEBUG: "${PYDEV_DEBUG}"
        ENVIRONMENT: test
    image: ghcr.io/opendatacube/ows:tests
    # Uncomment for use with non-dockerised postgres (for docker-compose 1.x)
    # network_mode: host
    environment:
      LOCAL_UID: ${LOCAL_UID:-1000}
      LOCAL_GID: ${LOCAL_GID:-1000}
      # Defaults are defined in .env file
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REQUEST_PAYER: ${AWS_REQUEST_PAYER}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      # Hard coded for now.
      ODC_ENVIRONMENT: default
      ODC_DEFAULT_INDEX_DRIVER: postgres
      ODC_OWSPOSTGIS_INDEX_DRIVER: postgis
      # Please switch to single entry url configuration for postgres url
      ODC_ODC2_INDEX_DRIVER: ${ODC_ODC2_INDEX_DRIVER}
      ODC_ODC2_DB_URL: ${ODC_ODC2_DB_URL}
      ODC_DEFAULT_DB_URL: ${ODC_DEFAULT_DB_URL}
      ODC_OWSPOSTGIS_DB_URL: ${ODC_OWSPOSTGIS_DB_URL}
      # for wait-for-db check
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      SERVER_DB_USERNAME: ${SERVER_DB_USERNAME}
      # Path from the PYTHONPATH to the config object (default PYTHONPATH is /src)
      PYTHONPATH: /src:${PYTHONPATH}
      DATACUBE_OWS_CFG: ${DATACUBE_OWS_CFG}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      # Talk to AWS without using credentials
      AWS_NO_SIGN_REQUEST: "${AWS_NO_SIGN_REQUEST}"
      # Enable Metrics
      PROMETHEUS_MULTIPROC_DIR: ${PROMETHEUS_MULTIPROC_DIR}
      # Dev flags
      FLASK_APP: "datacube_ows.startup_utils:create_app"
      FLASK_ENV: ${FLASK_ENV}
      PYDEV_DEBUG: "${PYDEV_DEBUG}"
      SENTRY_DSN: "${SENTRY_DSN}"
    volumes:
      - ${OWS_CFG_DIR}:${OWS_CFG_MOUNT_DIR}
      - ./:/src/
      - ./artifacts:/mnt/artifacts
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    # restart: always
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]

  postgres:
    image: postgis/postgis:18-3.6
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=35434
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    volumes:
      - ./docker/files/create-pg-databases.sh:/docker-entrypoint-initdb.d/create-pg-databases.sh
      - type: tmpfs
        target: /var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-q", "--port", "35434", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER"]
      timeout: 45s
      interval: 10s
      retries: 10
