# pyproject.toml
[build-system]
requires = ["setuptools>=65.5.1", "wheel>=0.38.1", "setuptools_scm[toml]>3.4"]

[tool.setuptools_scm]
write_to = "datacube_ows/_version.py"
fallback_version = "1.8.0-rc1.0"
