#!/bin/sh

RETRIES=10

# Wait until Database is ready
until pg_isready --dbname=$READY_PROBE_DB --host=$POSTGRES_HOSTNAME --username=$POSTGRES_USER || [ $RETRIES -eq 0 ]; do
  echo "Waiting for $READY_PROBE_DB databases, $((RETRIES-=1)) remaining attempts..."
  sleep 2
done

exec "$@"
