#!/bin/sh

RETRIES=10

# Wait until Database is ready
until pg_isready $PGISREADY_ARGS || [ $RETRIES -eq 0 ]; do
  echo "Waiting for $PGISREADY_ARGS database, $((RETRIES-=1)) remaining attempts..."
  sleep 2
done

exec "$@"
