#! /usr/bin/env bash

set -e

PGPASSWORD=$ADMIN_PASSWORD psql -h $DB_HOSTNAME -p $DB_PORT -U $ADMIN_USERNAME -d postgres <<-SQL
GRANT CREATE ON DATABASE "$DB_DATABASE" TO "$DB_USERNAME";
CREATE USER "$DB_USERNAME" WITH PASSWORD '$DB_PASSWORD';
GRANT "$DB_USERNAME" TO $ADMIN_USERNAME;
CREATE DATABASE "$DB_DATABASE" OWNER "$DB_USERNAME";
SQL
