name: Sandbox build and push latest

on:
  push:
    paths:
      - '.github/workflows/docker-ows.yml'
  pull_request:
    paths:
      - '.github/workflows/docker-ows.yml'

env:
  ORG: opendatacube
  IMAGE: ows
  DOCKER_USER: gadockersvc

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: |
        echo "Login to DockerHub as ${DOCKER_USER}"
        echo "${{ secrets.DockerPassword }}" | docker login -u "${DOCKER_USER}" --password-stdin

    - name: Build Docker Containers
      run: docker-compose up --build

    - name: Test ping
      run: curl localhost:8000/ping

    - name: Test WMS GetCapabilities
      run: curl http://localhost:8000/?service=WMS&version=1.3.0&request=GetCapabilities

    - name: Test WMTS GetCapabilities
      run: curl http://localhost:8000/?service=WMS&version=1.0.0&request=GetCapabilities

    - name: Test WCS GetCapabilities
      run: curl http://localhost:8000/?service=WCS&version=1.0.0&request=GetCapabilities

    - name: Test datacube-ows-update
      run: docker-compose exec datacube-ows-exec

    - name: Push to DockerHub (master branch only)
      if: github.ref == 'refs/heads/master'
      run: |
        tag=$(git describe --tags)
        docker tag ${ORG}/${IMAGE}:latest ${ORG}/ows:${tag}
        docker push ${ORG}/${IMAGE}:latest
        docker push ${ORG}/${IMAGE}:${tag}