---
name: Build Docker Image and push to GHCR

on:
  push:
    branches:
      - develop
    paths:
      - "**"
      - '!docs/**'
      - '!*.rst'
      - '!*.md'
      - '!.github/**'
      - '.github/workflows/docker.yml'
      - '!datacube_ows/__init__.py'
      - '!complementary_config_test/**'
      - '!integration_tests/**'
      - '!tests/**'
      - '!wms_xsds/**'

  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: opendatacube/ows

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    name: Build Docker image and push to GHCR
    timeout-minutes: 15
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # This is required for requesting the JWT+cosign
      contents: read    # This is required for actions/checkout
      packages: write  # This is required for pushing to ghcr
      attestations: write # This is required for pushing the attestation
      artifact-metadata: write # This is required for creating the storage record

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Log in to the Container registry
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Get Git commit timestamps
        run: |
          TIMESTAMP=$(git log -1 --pretty=%ct pyproject.toml uv.lock datacube_ows)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      - name: Attest Docker image
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Sign the Docker image
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes --recursive {}@${DIGEST}
