---
name: dockerfile Linting

on:
  pull_request:
    branches:
      - 'develop'
      - 'develop-1.9'
    paths:
      - 'Dockerfile'
      - '.github/workflows/dockerfile-lint.yml'

  push:
    branches:
      - 'develop'
    paths:
      - 'Dockerfile'
      - '.github/workflows/dockerfile-lint.yml'


# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          ignore: DL3008,DL3002,DL3013,DL3059,SC2102
