---
name: Doc Preview

on:
  pull_request:
    branches:
      - 'master'

  workflow_dispatch:

permissions:
  pull-requests: write

jobs:

  documentation-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "datacube-ows"
