---
name: Code Linting

on:
  pull_request:
    branches: &branches
      - 'develop'
      - 'develop-1.8'
    paths: &paths
      - '**'
      - '!docs/**'
      - '!*.rst'
      - '!*.md'
      - '!datacube_ows/__init__.py'
      - '!.github/**'
      - '.github/workflows/lint.yml'

  push:
    branches: *branches
    paths: *paths

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        lintcommand:
          - "pylint -j 2 datacube_ows --disable=C,R,W,E1136"
          - "ruff check --output-format=github"
          - "mypy datacube_ows integration_tests/cfg integration_tests/test_[a-i]*.py integration_tests/test_[n-z]*.py tests/test_c*.py tests/test_[p-r]*.py tests/test_w*.py"
    name: Linting
    steps:
      - name: checkout git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          # Prevent cache poisoning for releases.
          enable-cache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --locked --extra=dev
      - name: Detect number of cores
        run: |
          CORES=$(nproc)
          echo "MYPY_NUM_WORKERS=$CORES" >> $GITHUB_ENV
      - name: run linter
        run: |
          uv run ${LINT_COMMAND}
        env:
          LINT_COMMAND: ${{matrix.lintcommand}}
          UV_PYTHON_PREFERENCE: managed
          MYPY_NUM_WORKERS: ${{ env.MYPY_NUM_WORKERS }}
