name: Doc QA
on:
  pull_request:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  pyspellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: igsekor/pyspelling-any@v0.0.2
        name: Spellcheck

  documentation-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "datacube-ows"
